export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAIL = "ADMIN_REGISTER_FAIL";

export const ADMIN_SIGNIN_REQUEST = "ADMIN_SIGNIN_REQUEST";
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS";
export const ADMIN_SIGNIN_FAIL = "ADMIN_SIGNIN_FAIL";
export const ADMIN_SIGNOUT = "ADMIN_SIGNOUT";

export const CREATE_STORE_REQUEST = "CREATE_STORE_REQUEST";
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS";
export const CREATE_STORE_FAIL = "CREATE_STORE_FAIL";
export const CREATE_STORE_RESET = "CREATE_STORE_RESET";

export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAIL = "UPDATE_STORE_FAIL";
export const UPDATE_STORE_RESET = "UPDATE_STORE_RESET";

export const LIST_STORE_REQUEST = "LIST_STORE_REQUEST";
export const LIST_STORE_SUCCESS = "LIST_STORE_SUCCESS";
export const LIST_STORE_FAIL = "LIST_STORE_FAIL";
export const LIST_STORE_RESET = "LIST_STORE_RESET";

export const STORE_SIGNIN_REQUEST = "STORE_SIGNIN_REQUEST";
export const DELETE_STORE_REQUEST = "DELETE_STORE_REQUEST";
export const STORE_SIGNIN_SUCCESS = "STORE_SIGNIN_SUCCESS";
export const STORE_SIGNIN_FAIL = "STORE_SIGNIN_FAIL";
export const DELETE_STORE_FAIL = "DELETE_STORE_FAIL";
export const STORE_SIGNIN_RESET = "STORE_SIGNIN_RESET";
export const STORE_SIGNOUT = "STORE_SIGNOUT";

export const STORE_COVER_REQUEST = "STORE_COVER_REQUEST";
export const STORE_COVER_SUCCESS = "STORE_COVER_SUCCESS";
export const STORE_COVER_FAIL = "STORE_COVER_FAIL";
export const STORE_COVER_RESET = "STORE_COVER_RESET";

export const LIST_COVER_REQUEST = "LIST_COVER_REQUEST";
export const LIST_COVER_SUCCESS = "LIST_COVER_SUCCESS";
export const LIST_COVER_FAIL = "LIST_COVER_FAIL";
export const LIST_COVER_RESET = "LIST_COVER_RESET";

export const DELETE_COVER_REQUEST = "DELETE_COVER_REQUEST";
export const DELETE_COVER_SUCCESS = "DELETE_COVER_SUCCESS";
export const DELETE_COVER_FAIL = "DELETE_COVER_FAIL";
export const DELETE_COVER_RESET = "DELETE_COVER_RESET";

export const UPDATE_COVER_REQUEST = "UPDATE_COVER_REQUEST";
export const UPDATE_COVER_SUCCESS = "UPDATE_COVER_SUCCESS";
export const UPDATE_COVER_FAIL = "UPDATE_COVER_FAIL";
export const UPDATE_COVER_RESET = "UPDATE_COVER_RESET";
