export const CREATE_BOOKING_REQUEST = "STORE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "STORE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAIL = "STORE_BOOKING_FAIL";
export const CREATE_BOOKING_RESET = "STORE_BOOKING_RESET";

export const LIST_BOOKING_REQUEST = "LIST_BOOKING_REQUEST";
export const LIST_BOOKING_SUCCESS = "LIST_BOOKING_SUCCESS";
export const LIST_BOOKING_FAIL = "LIST_BOOKING_FAIL";
export const LIST_BOOKING_RESET = "LIST_BOOKING_RESET";

export const DELETE_BOOKING_REQUEST = "DELETE_BOOKING_REQUEST";
export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_FAIL = "DELETE_BOOKING_FAIL";
export const DELETE_BOOKING_RESET = "DELETE_BOOKING_RESET";

export const UPDATE_BOOKING_REQUEST = "UPDATE_BOOKING_REQUEST";
export const UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS";
export const UPDATE_BOOKING_FAIL = "UPDATE_BOOKING_FAIL";
export const UPDATE_BOOKING_RESET = "UPDATE_BOOKING_RESET";
